In [ ]:
from pathlib import Path
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1200)
pd.set_option("display.max_rows", 200)

In [ ]:
INPUT_CSV_PATH = r"D:\ДЛ\data\polymarket_culture_2024_to_now_closed_resolved\culture_markets_2024_to_now_closed_resolved_yesno.csv"
input_path = Path(INPUT_CSV_PATH)
print("INPUT_CSV_PATH =", input_path)
print("Exists:", input_path.exists())

INPUT_CSV_PATH = D:\ДЛ\data\polymarket_culture_2024_to_now_closed_resolved\culture_markets_2024_to_now_closed_resolved_yesno.csv
Exists: True

In [ ]:
if not input_path.exists():
    raise FileNotFoundError(f"Файл не найден: {input_path}")

df = pd.read_csv(input_path)
print("Shape:", df.shape)
display(df.head(5))

Shape: (19649, 51)

C:\Users\User\AppData\Local\Temp\ipykernel_13040\2700825798.py:4: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_path)

   market_id                                       condition_id                                           question                                               slug  category                 createdAt                    updatedAt                 startDate               endDate              closedTime  active  closed  archived  acceptingOrders marketType  formatType    liquidity         volume  liquidityNum  volumeNum  bestBid  bestAsk  lastTradePrice  spread umaResolutionStatus   outcomes_raw outcomePrices_raw                                         tag_labels                                          tag_slugs                                          tags_json categories_json  event_id                                    event_slug                                    event_title  event_category  event_subcategory        event_creationDate         event_endDate           event_createdAt              event_updatedAt                      createdAt_dt  active_simplified  closed_simplified  archived_simplified  accepting_orders_simplified  token_count winner_outcome  is_binary_yes_no                                        tokens_json resolution_timestamp_best_effort  final_outcome
0     253580  0x45847351990b89f654185d0c331ff8f950779264ffb1...      Will the Epstein documents name Jimmy Kimmel?       will-the-epstein-documents-name-jimmy-kimmel       NaN  2024-01-03T14:10:04.782Z  2024-04-22T22:40:52.202728Z  2024-01-03T14:11:38.915Z  2024-02-29T00:00:00Z  2024-03-01 07:17:34+00    True    True     False             True     normal         NaN     27.28800   30052.317210         27.29   30052.32      0.0      1.0             0.0     1.0            resolved  ["Yes", "No"]        ["0", "1"]  ["Epstein", "jimmy kimmel", "court cases", "le...  ["epstein", "jimmy-kimmel", "court-cases", "le...  [{"id": "756", "label": "Epstein", "slug": "ep...              []    903183  will-the-epstein-documents-name-jimmy-kimmel  Will the Epstein documents name Jimmy Kimmel?             NaN                NaN  2024-01-03T14:12:59.929Z  2024-02-29T00:00:00Z  2024-01-03T14:10:04.895Z  2024-04-25T21:25:14.849751Z  2024-01-03 14:10:04.782000+00:00               True               True                False                         True            2             No              True  [{"token_id": "1115107825852446580080896045340...           2024-03-01 07:17:34+00              0
1     253845  0xb2e69f44b6c173bc6f5ef1b679c5a3cc73cafef1fbf2...  Will "Oppenheimer" win the Oscar for Best Pict...    will-oppenheimer-win-the-oscar-for-best-picture       NaN  2024-01-12T19:09:10.051Z     2024-03-12T05:29:53.154Z      2024-01-16T17:44:00Z  2024-03-09T00:00:00Z  2024-03-11 05:32:30+00    True    True     False             True     normal         NaN   5155.20623  168512.627925       5155.21  168512.63      0.0      1.0             0.0     1.0            proposed  ["Yes", "No"]        ["1", "0"]  ["oppenheimer", "Oscars", "best picture", "fil...  ["oppenheimer", "oscars", "best-picture", "fil...  [{"id": "1020", "label": "oppenheimer", "slug"...              []    903246                      oscars-2024-best-picture                           Oscars: Best Picture             NaN                NaN   2024-01-16T17:53:16.16Z  2024-03-10T00:00:00Z  2024-01-12T19:09:10.135Z      2024-03-12T05:30:48.98Z  2024-01-12 19:09:10.051000+00:00               True               True                False                         True            2            Yes              True  [{"token_id": "6027318848856724957823623639973...           2024-03-11 05:32:30+00              1
2     253846  0x997439c67162f879438a67d4547942dbe470709f6b3e...  Will "Poor Things" win the Oscar for Best Pict...    will-poor-things-win-the-oscar-for-best-picture       NaN  2024-01-12T19:09:10.099Z     2024-03-12T02:53:57.522Z      2024-01-16T17:44:00Z  2024-03-09T00:00:00Z  2024-03-11 05:32:46+00    True    True     False             True     normal         NaN  10708.15889   81772.245238      10708.16   81772.25      0.0      1.0             0.0     1.0            proposed  ["Yes", "No"]        ["0", "1"]  ["poor things", "Oscars", "best picture", "Mov...  ["poor-things", "oscars", "best-picture", "mov...  [{"id": "1021", "label": "poor things", "slug"...              []    903246                      oscars-2024-best-picture                           Oscars: Best Picture             NaN                NaN   2024-01-16T17:53:16.16Z  2024-03-10T00:00:00Z  2024-01-12T19:09:10.135Z      2024-03-12T05:30:48.98Z  2024-01-12 19:09:10.099000+00:00               True               True                False                         True            2             No              True  [{"token_id": "1019929159450458582676240232291...           2024-03-11 05:32:46+00              0
3     253847  0x84336ff58b9a4abcd805e56783d7353eb8159aea6ef0...  Will "Killers of the Flower Moon" win the Osca...  will-killers-of-the-flower-moon-win-the-oscar-...       NaN  2024-01-12T19:11:13.966Z     2024-03-12T02:53:57.221Z      2024-01-16T17:44:00Z  2024-03-09T00:00:00Z  2024-03-11 05:32:28+00    True    True     False             True     normal         NaN   3373.62300   90746.289502       3373.62   90746.29      0.0      1.0             0.0     1.0            proposed  ["Yes", "No"]        ["0", "1"]  ["Movies", "Oscars", "killers of the flower mo...  ["movies", "oscars", "killers-of-the-flower-mo...  [{"id": "53", "label": "Movies", "slug": "movi...              []    903246                      oscars-2024-best-picture                           Oscars: Best Picture             NaN                NaN   2024-01-16T17:53:16.16Z  2024-03-10T00:00:00Z  2024-01-12T19:09:10.135Z      2024-03-12T05:30:48.98Z  2024-01-12 19:11:13.966000+00:00               True               True                False                         True            2             No              True  [{"token_id": "1405945025455950224826842010871...           2024-03-11 05:32:28+00              0
4     253848  0xfecc393922d70836f9bf45558f161326e0fa3150e110...      Will "Barbie" win the Oscar for Best Picture?         will-barbie-win-the-oscar-for-best-picture       NaN  2024-01-12T19:11:53.477Z     2024-03-12T02:53:57.733Z      2024-01-16T17:45:00Z  2024-03-09T00:00:00Z  2024-03-11 05:32:56+00    True    True     False             True     normal         NaN  12860.80252   74684.976029      12860.80   74684.98      0.0      1.0             0.0     1.0            proposed  ["Yes", "No"]        ["0", "1"]  ["barbie", "Oscars", "best picture", "film", "...  ["barbie", "oscars", "best-picture", "film", "...  [{"id": "1019", "label": "barbie", "slug": "ba...              []    903246                      oscars-2024-best-picture                           Oscars: Best Picture             NaN                NaN   2024-01-16T17:53:16.16Z  2024-03-10T00:00:00Z  2024-01-12T19:09:10.135Z      2024-03-12T05:30:48.98Z  2024-01-12 19:11:53.477000+00:00               True               True                False                         True            2             No              True  [{"token_id": "5176050547152421363312085301978...           2024-03-11 05:32:56+00              0

In [ ]:
# базовая инфа
print("Rows, cols:", df.shape)
print("\nColumns:")
for i, col in enumerate(df.columns, 1):
    print(f"{i:>3}. {col}")

print("\nDtypes:")
display(df.dtypes.to_frame("dtype"))

Rows, cols: (19649, 51)

Columns:
  1. market_id
  2. condition_id
  3. question
  4. slug
  5. category
  6. createdAt
  7. updatedAt
  8. startDate
  9. endDate
 10. closedTime
 11. active
 12. closed
 13. archived
 14. acceptingOrders
 15. marketType
 16. formatType
 17. liquidity
 18. volume
 19. liquidityNum
 20. volumeNum
 21. bestBid
 22. bestAsk
 23. lastTradePrice
 24. spread
 25. umaResolutionStatus
 26. outcomes_raw
 27. outcomePrices_raw
 28. tag_labels
 29. tag_slugs
 30. tags_json
 31. categories_json
 32. event_id
 33. event_slug
 34. event_title
 35. event_category
 36. event_subcategory
 37. event_creationDate
 38. event_endDate
 39. event_createdAt
 40. event_updatedAt
 41. createdAt_dt
 42. active_simplified
 43. closed_simplified
 44. archived_simplified
 45. accepting_orders_simplified
 46. token_count
 47. winner_outcome
 48. is_binary_yes_no
 49. tokens_json
 50. resolution_timestamp_best_effort
 51. final_outcome

Dtypes:

                                    dtype
market_id                           int64
condition_id                       object
question                           object
slug                               object
category                          float64
createdAt                          object
updatedAt                          object
startDate                          object
endDate                            object
closedTime                         object
active                               bool
closed                               bool
archived                             bool
acceptingOrders                      bool
marketType                         object
formatType                        float64
liquidity                         float64
volume                            float64
liquidityNum                      float64
volumeNum                         float64
bestBid                           float64
bestAsk                           float64
lastTradePrice                    float64
spread                            float64
umaResolutionStatus                object
outcomes_raw                       object
outcomePrices_raw                  object
tag_labels                         object
tag_slugs                          object
tags_json                          object
categories_json                    object
event_id                            int64
event_slug                         object
event_title                        object
event_category                    float64
event_subcategory                 float64
event_creationDate                 object
event_endDate                      object
event_createdAt                    object
event_updatedAt                    object
createdAt_dt                       object
active_simplified                    bool
closed_simplified                    bool
archived_simplified                  bool
accepting_orders_simplified          bool
token_count                         int64
winner_outcome                     object
is_binary_yes_no                     bool
tokens_json                        object
resolution_timestamp_best_effort   object
final_outcome                       int64

In [ ]:
# пропуски
missing_summary = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_pct": (df.isna().mean() * 100).round(2),
}).sort_values(["missing_count", "missing_pct"], ascending=False)

display(missing_summary)

                                  missing_count  missing_pct
category                                  19649       100.00
formatType                                19649       100.00
event_category                            19649       100.00
event_subcategory                         19649       100.00
marketType                                19505        99.27
liquidity                                 17559        89.36
liquidityNum                              17559        89.36
bestBid                                   15547        79.12
volume                                     1773         9.02
volumeNum                                  1773         9.02
lastTradePrice                              554         2.82
endDate                                     269         1.37
startDate                                   230         1.17
event_endDate                                95         0.48
event_creationDate                            4         0.02
market_id                                     0         0.00
condition_id                                  0         0.00
question                                      0         0.00
slug                                          0         0.00
createdAt                                     0         0.00
updatedAt                                     0         0.00
closedTime                                    0         0.00
active                                        0         0.00
closed                                        0         0.00
archived                                      0         0.00
acceptingOrders                               0         0.00
bestAsk                                       0         0.00
spread                                        0         0.00
umaResolutionStatus                           0         0.00
outcomes_raw                                  0         0.00
outcomePrices_raw                             0         0.00
tag_labels                                    0         0.00
tag_slugs                                     0         0.00
tags_json                                     0         0.00
categories_json                               0         0.00
event_id                                      0         0.00
event_slug                                    0         0.00
event_title                                   0         0.00
event_createdAt                               0         0.00
event_updatedAt                               0         0.00
createdAt_dt                                  0         0.00
active_simplified                             0         0.00
closed_simplified                             0         0.00
archived_simplified                           0         0.00
accepting_orders_simplified                   0         0.00
token_count                                   0         0.00
winner_outcome                                0         0.00
is_binary_yes_no                              0         0.00
tokens_json                                   0         0.00
resolution_timestamp_best_effort              0         0.00
final_outcome                                 0         0.00

In [ ]:
# поиск дубликатов
exact_duplicates = df.duplicated().sum()
print("Полных дубликатов строк:", exact_duplicates)

dup_checks = {}

for col in ["market_id", "condition_id", "question", "slug"]:
    if col in df.columns:
        dup_checks[col] = int(df[col].duplicated().sum())

print("\nДубликаты по ключевым колонкам:")
for k, v in dup_checks.items():
    print(f"{k}: {v}")

for col in ["market_id", "condition_id"]:
    if col in df.columns:
        dup_rows = df[df[col].duplicated(keep=False)].sort_values(col)
        print(f"\nСтроки с дубликатами по {col}: {len(dup_rows)}")
        if len(dup_rows) > 0:
            display(dup_rows.head(20))

Полных дубликатов строк: 0

Дубликаты по ключевым колонкам:
market_id: 0
condition_id: 0
question: 1080
slug: 0

Строки с дубликатами по market_id: 0

Строки с дубликатами по condition_id: 0

In [ ]:
# выполнение бинарности ответов
if "is_binary_yes_no" not in df.columns:
    print("Колонка is_binary_yes_no отсутствует.")
    bad_is_binary = pd.DataFrame()
else:
    mask_bad_is_binary = df["is_binary_yes_no"].fillna(False) != True
    bad_is_binary = df.loc[mask_bad_is_binary].copy()
    print("Количество строк, где is_binary_yes_no != True:", len(bad_is_binary))
    display(bad_is_binary.head(50))

Количество строк, где is_binary_yes_no != True: 0

Empty DataFrame
Columns: [market_id, condition_id, question, slug, category, createdAt, updatedAt, startDate, endDate, closedTime, active, closed, archived, acceptingOrders, marketType, formatType, liquidity, volume, liquidityNum, volumeNum, bestBid, bestAsk, lastTradePrice, spread, umaResolutionStatus, outcomes_raw, outcomePrices_raw, tag_labels, tag_slugs, tags_json, categories_json, event_id, event_slug, event_title, event_category, event_subcategory, event_creationDate, event_endDate, event_createdAt, event_updatedAt, createdAt_dt, active_simplified, closed_simplified, archived_simplified, accepting_orders_simplified, token_count, winner_outcome, is_binary_yes_no, tokens_json, resolution_timestamp_best_effort, final_outcome]
Index: []

In [ ]:
if "token_count" not in df.columns:
    print("Колонка token_count отсутствует.")
    bad_token_count = pd.DataFrame()
else:
    token_count_numeric = pd.to_numeric(df["token_count"], errors="coerce")
    mask_bad_token_count = token_count_numeric != 2
    bad_token_count = df.loc[mask_bad_token_count].copy()
    print("Количество строк, где token_count != 2:", len(bad_token_count))
    display(bad_token_count.head(50))

    print("\nРаспределение token_count:")
    display(token_count_numeric.value_counts(dropna=False).sort_index())

Количество строк, где token_count != 2: 0

Empty DataFrame
Columns: [market_id, condition_id, question, slug, category, createdAt, updatedAt, startDate, endDate, closedTime, active, closed, archived, acceptingOrders, marketType, formatType, liquidity, volume, liquidityNum, volumeNum, bestBid, bestAsk, lastTradePrice, spread, umaResolutionStatus, outcomes_raw, outcomePrices_raw, tag_labels, tag_slugs, tags_json, categories_json, event_id, event_slug, event_title, event_category, event_subcategory, event_creationDate, event_endDate, event_createdAt, event_updatedAt, createdAt_dt, active_simplified, closed_simplified, archived_simplified, accepting_orders_simplified, token_count, winner_outcome, is_binary_yes_no, tokens_json, resolution_timestamp_best_effort, final_outcome]
Index: []

Распределение token_count:

token_count
2    19649
Name: count, dtype: int64

In [ ]:
if "umaResolutionStatus" not in df.columns:
    print("Колонка umaResolutionStatus отсутствует.")
    status_counts = pd.Series(dtype="int64")
else:
    status_series = (
        df["umaResolutionStatus"]
        .astype("string")
        .str.strip()
        .str.lower()
    )
    status_counts = status_series.fillna("<NA>").value_counts(dropna=False)

    print("Распределение umaResolutionStatus:")
    display(status_counts.to_frame("count"))

    resolved_count = int((status_series == "resolved").sum())
    proposed_count = int((status_series == "proposed").sum())
    other_values = sorted(set(status_series.dropna().unique()) - {"resolved", "proposed"})

    print("resolved:", resolved_count)
    print("proposed:", proposed_count)
    print("other values:", other_values if other_values else "нет")

Распределение umaResolutionStatus:

                     count
umaResolutionStatus
resolved             19571
proposed                78

resolved: 19571
proposed: 78
other values: нет

In [ ]:
#удаление лишнего
COLUMNS_TO_DROP = [
    "market_id",
    "condition_id",
    "slug",
    "category",
    "updatedAt",
    "closedTime",
    "active",
    "closed",
    "archived",
    "acceptingOrders",
    "marketType",
    "formatType",
    "liquidity",
    "volume",
    "liquidityNum",
    "volumeNum",
    "bestBid",
    "bestAsk",
    "lastTradePrice",
    "spread",
    "outcomes_raw",
    "outcomePrices_raw",
    "tag_labels",
    "tag_slugs",
    "tags_json",
    "categories_json",
    "event_id",
    "event_slug",
    "event_title",
    "event_category",
    "event_subcategory",
    "event_creationDate",
    "event_endDate",
    "event_createdAt",
    "event_updatedAt",
    "createdAt_dt",
    "active_simplified",
    "closed_simplified",
    "archived_simplified",
    "accepting_orders_simplified",
    "tokens_json",
    "resolution_timestamp_best_effort",
    "is_binary_yes_no",
    "token_count",
    "createdAt"
]

existing_to_drop = [c for c in COLUMNS_TO_DROP if c in df.columns]
missing_to_drop = [c for c in COLUMNS_TO_DROP if c not in df.columns]

print("Будут удалены колонки:", len(existing_to_drop))
display(pd.DataFrame({"drop_column": existing_to_drop}))

print("\nНе найдены в таблице:", len(missing_to_drop))
display(pd.DataFrame({"missing_column": missing_to_drop}))

Будут удалены колонки: 45

                         drop_column
0                          market_id
1                       condition_id
2                               slug
3                           category
4                          updatedAt
5                         closedTime
6                             active
7                             closed
8                           archived
9                    acceptingOrders
10                        marketType
11                        formatType
12                         liquidity
13                            volume
14                      liquidityNum
15                         volumeNum
16                           bestBid
17                           bestAsk
18                    lastTradePrice
19                            spread
20                      outcomes_raw
21                 outcomePrices_raw
22                        tag_labels
23                         tag_slugs
24                         tags_json
25                   categories_json
26                          event_id
27                        event_slug
28                       event_title
29                    event_category
30                 event_subcategory
31                event_creationDate
32                     event_endDate
33                   event_createdAt
34                   event_updatedAt
35                      createdAt_dt
36                 active_simplified
37                 closed_simplified
38               archived_simplified
39       accepting_orders_simplified
40                       tokens_json
41  resolution_timestamp_best_effort
42                  is_binary_yes_no
43                       token_count
44                         createdAt

Не найдены в таблице: 0

Empty DataFrame
Columns: [missing_column]
Index: []

In [ ]:
final_df = df.drop(columns=existing_to_drop, errors="ignore").copy()

print("Shape исходной таблицы:", df.shape)
print("Shape final_df после удаления колонок:", final_df.shape)

print("\nОставшиеся колонки:")
for i, col in enumerate(final_df.columns, 1):
    print(f"{i:>3}. {col}")

display(final_df.head(10))

Shape исходной таблицы: (19649, 51)
Shape final_df после удаления колонок: (19649, 6)

Оставшиеся колонки:
  1. question
  2. startDate
  3. endDate
  4. umaResolutionStatus
  5. winner_outcome
  6. final_outcome

                                            question                 startDate               endDate umaResolutionStatus winner_outcome  final_outcome
0      Will the Epstein documents name Jimmy Kimmel?  2024-01-03T14:11:38.915Z  2024-02-29T00:00:00Z            resolved             No              0
1  Will "Oppenheimer" win the Oscar for Best Pict...      2024-01-16T17:44:00Z  2024-03-09T00:00:00Z            proposed            Yes              1
2  Will "Poor Things" win the Oscar for Best Pict...      2024-01-16T17:44:00Z  2024-03-09T00:00:00Z            proposed             No              0
3  Will "Killers of the Flower Moon" win the Osca...      2024-01-16T17:44:00Z  2024-03-09T00:00:00Z            proposed             No              0
4      Will "Barbie" win the Oscar for Best Picture?      2024-01-16T17:45:00Z  2024-03-09T00:00:00Z            proposed             No              0
5  Will "The Holdovers" win the Oscar for Best Pi...      2024-01-16T17:47:00Z  2024-03-09T00:00:00Z            proposed             No              0
6  Will "Past Lives" win the Oscar for Best Picture?      2024-01-16T17:48:00Z  2024-03-09T00:00:00Z            proposed             No              0
7     Will "Maestro" win the Oscar for Best Picture?      2024-01-16T17:49:00Z  2024-03-09T00:00:00Z            proposed             No              0
8  Will "Anatomy of a Fall" win the Oscar for Bes...      2024-01-16T17:50:00Z  2024-03-09T00:00:00Z            proposed             No              0
9  Will "American Fiction" win the Oscar for Best...      2024-01-16T17:51:00Z  2024-03-09T00:00:00Z            proposed             No              0

In [ ]:
final_missing_summary = pd.DataFrame({
    "missing_count": final_df.isna().sum(),
    "missing_pct": (final_df.isna().mean() * 100).round(2),
}).sort_values(["missing_count", "missing_pct"], ascending=False)

display(final_missing_summary)

                     missing_count  missing_pct
endDate                        269         1.37
startDate                      230         1.17
question                         0         0.00
umaResolutionStatus              0         0.00
winner_outcome                   0         0.00
final_outcome                    0         0.00

In [ ]:
bad_rows_mask = (
    final_df["umaResolutionStatus"].astype("string").str.strip().str.lower().eq("proposed")
    | final_df["endDate"].isna()
    | final_df["startDate"].isna()
)

print("Строк к удалению:", int(bad_rows_mask.sum()))

final_df = final_df.loc[~bad_rows_mask].copy()

print("Новый размер final_df:", final_df.shape)

Строк к удалению: 577
Новый размер final_df: (19072, 6)

In [ ]:
question_dup_mask = final_df["question"].astype("string").str.strip().duplicated(keep=False)

dup_questions_df = final_df.loc[question_dup_mask].copy()

print("Количество строк, у которых question совпадает с другой строкой:", len(dup_questions_df))
print("Количество уникальных текстов question, которые повторяются:", dup_questions_df["question"].nunique())

dup_counts = (
    dup_questions_df["question"]
    .value_counts()
    .rename_axis("question")
    .reset_index(name="count")
)

print("\nТоп-3 повторяющихся question:")
display(dup_counts.head(3))

top3_questions = dup_counts.head(3)["question"].tolist()

sample_cols = [c for c in [
    "question",
    "createdAt",
    "endDate",
    "umaResolutionStatus",
    "winner_outcome",
    "final_outcome"
] if c in final_df.columns]

print("\nТри примера повторяющихся событий:")
display(
    final_df.loc[final_df["question"].isin(top3_questions), sample_cols]
    .sort_values(["question"] + ([c for c in ["createdAt"] if c in sample_cols]))
)

Количество строк, у которых question совпадает с другой строкой: 1458
Количество уникальных текстов question, которые повторяются: 443

Топ-3 повторяющихся question:

                                            question  count
0  Will "Man I Need - Olivia Dean" be the #1 song...     15
1  Will MrBeast's next video get 55 million or mo...     13
2  Will MrBeast's next video get between 80 and 9...     13

Три примера повторяющихся событий:

                                                question               endDate umaResolutionStatus winner_outcome  final_outcome
13144  Will "Man I Need - Olivia Dean" be the #1 song...  2026-01-23T00:00:00Z            resolved             No              0
17824  Will "Man I Need - Olivia Dean" be the #1 song...  2026-03-27T00:00:00Z            resolved             No              0
17443  Will "Man I Need - Olivia Dean" be the #1 song...  2026-03-20T00:00:00Z            resolved             No              0
16971  Will "Man I Need - Olivia Dean" be the #1 song...  2026-03-13T00:00:00Z            resolved             No              0
16479  Will "Man I Need - Olivia Dean" be the #1 song...  2026-03-06T00:00:00Z            resolved             No              0
15929  Will "Man I Need - Olivia Dean" be the #1 song...  2026-02-27T00:00:00Z            resolved             No              0
15919  Will "Man I Need - Olivia Dean" be the #1 song...  2026-02-27T00:00:00Z            resolved             No              0
15414  Will "Man I Need - Olivia Dean" be the #1 song...  2026-02-20T00:00:00Z            resolved             No              0
15404  Will "Man I Need - Olivia Dean" be the #1 song...  2026-02-20T00:00:00Z            resolved             No              0
14907  Will "Man I Need - Olivia Dean" be the #1 song...  2026-02-13T00:00:00Z            resolved             No              0
14281  Will "Man I Need - Olivia Dean" be the #1 song...  2026-02-06T00:00:00Z            resolved             No              0
13687  Will "Man I Need - Olivia Dean" be the #1 song...  2026-01-30T00:00:00Z            resolved             No              0
12004  Will "Man I Need - Olivia Dean" be the #1 song...  2026-01-16T00:00:00Z            resolved             No              0
11490  Will "Man I Need - Olivia Dean" be the #1 song...  2026-01-09T00:00:00Z            resolved             No              0
19447  Will "Man I Need - Olivia Dean" be the #1 song...  2026-04-17T00:00:00Z            resolved             No              0
6577   Will MrBeast's next video get 55 million or mo...  2026-01-31T00:00:00Z            resolved             No              0
4277   Will MrBeast's next video get 55 million or mo...  2025-12-31T00:00:00Z            resolved             No              0
4524   Will MrBeast's next video get 55 million or mo...  2025-12-31T00:00:00Z            resolved             No              0
4793   Will MrBeast's next video get 55 million or mo...  2025-12-31T00:00:00Z            resolved             No              0
5050   Will MrBeast's next video get 55 million or mo...  2025-12-31T00:00:00Z            resolved             No              0
5435   Will MrBeast's next video get 55 million or mo...  2025-12-31T00:00:00Z            resolved             No              0
6268   Will MrBeast's next video get 55 million or mo...  2025-12-31T00:00:00Z            resolved             No              0
15527  Will MrBeast's next video get 55 million or mo...  2026-05-31T00:00:00Z            resolved             No              0
10768  Will MrBeast's next video get 55 million or mo...  2026-03-31T00:00:00Z            resolved             No              0
3978   Will MrBeast's next video get 55 million or mo...  2025-12-31T00:00:00Z            resolved             No              0
13990  Will MrBeast's next video get 55 million or mo...  2026-05-31T00:00:00Z            resolved             No              0
18479  Will MrBeast's next video get 55 million or mo...  2026-05-31T00:00:00Z            resolved             No              0
12000  Will MrBeast's next video get 55 million or mo...  2026-03-31T00:00:00Z            resolved             No              0
7523   Will MrBeast's next video get between 80 and 9...  2026-01-31T00:00:00Z            resolved             No              0
6581   Will MrBeast's next video get between 80 and 9...  2026-01-31T00:00:00Z            resolved             No              0
14237  Will MrBeast's next video get between 80 and 9...  2026-05-31T00:00:00Z            resolved             No              0
15531  Will MrBeast's next video get between 80 and 9...  2026-05-31T00:00:00Z            resolved             No              0
8809   Will MrBeast's next video get between 80 and 9...  2026-01-31T00:00:00Z            resolved             No              0
12488  Will MrBeast's next video get between 80 and 9...  2026-03-31T00:00:00Z            resolved             No              0
16587  Will MrBeast's next video get between 80 and 9...  2026-03-31T00:00:00Z            resolved            Yes              1
9185   Will MrBeast's next video get between 80 and 9...  2026-03-31T00:00:00Z            resolved             No              0
17473  Will MrBeast's next video get between 80 and 9...  2026-03-31T00:00:00Z            resolved            Yes              1
10005  Will MrBeast's next video get between 80 and 9...  2026-03-31T00:00:00Z            resolved             No              0
18468  Will MrBeast's next video get between 80 and 9...  2026-05-31T00:00:00Z            resolved            Yes              1
7930   Will MrBeast's next video get between 80 and 9...  2026-01-31T00:00:00Z            resolved             No              0
11113  Will MrBeast's next video get between 80 and 9...  2026-03-31T00:00:00Z            resolved             No              0

In [ ]:
final_df = final_df.drop(columns=["umaResolutionStatus", "winner_outcome"], errors="ignore").copy()
final_df.head(5)

                                            question                 startDate               endDate  final_outcome
0      Will the Epstein documents name Jimmy Kimmel?  2024-01-03T14:11:38.915Z  2024-02-29T00:00:00Z              0
11          Will 2024 be the hottest year on record?  2024-01-16T21:50:24.112Z  2025-03-01T00:00:00Z              1
13  Andrew Tate guilty of human trafficking in 2024?  2024-01-17T21:17:16.187Z  2024-12-30T12:00:00Z              0
38                     Will America ban Zyn in 2024?  2024-01-25T17:27:39.723Z  2024-12-31T00:00:00Z              0
67             Will 'Deadpool 3' gross most in 2024?      2024-01-31T23:47:00Z  2024-12-29T00:00:00Z              0

## 13) Экспорт в CSV и Excel

Сохраняем рядом с исходным файлом.

Имя будет таким:
- `исходное_имя_FINAL.csv`
- `исходное_имя_FINAL.xlsx`

In [ ]:
base_stem = input_path.stem
output_dir = input_path.parent

csv_out = output_dir / f"{base_stem}_FINAL.csv"
xlsx_out = output_dir / f"{base_stem}_FINAL.xlsx"

final_df.to_csv(csv_out, index=False)

try:
    final_df.to_excel(xlsx_out, index=False)
    excel_status = "Excel сохранён успешно."
except Exception as e:
    excel_status = f"Ошибка при сохранении Excel: {e}"

print("CSV:", csv_out)
print("XLSX:", xlsx_out)
print(excel_status)

CSV: D:\ДЛ\data\polymarket_culture_2024_to_now_closed_resolved\culture_markets_2024_to_now_closed_resolved_yesno_FINAL.csv
XLSX: D:\ДЛ\data\polymarket_culture_2024_to_now_closed_resolved\culture_markets_2024_to_now_closed_resolved_yesno_FINAL.xlsx
Ошибка при сохранении Excel: No module named 'openpyxl'

## 14) Итоговая проверка сохранённых файлов

In [ ]:
print("CSV exists:", csv_out.exists(), "|", csv_out)
print("XLSX exists:", xlsx_out.exists(), "|", xlsx_out)

if csv_out.exists():
    check_df = pd.read_csv(csv_out)
    print("Shape сохранённого CSV:", check_df.shape)
    display(check_df.head(5))

CSV exists: True | D:\ДЛ\data\polymarket_culture_2024_to_now_closed_resolved\culture_markets_2024_to_now_closed_resolved_yesno_FINAL.csv
XLSX exists: False | D:\ДЛ\data\polymarket_culture_2024_to_now_closed_resolved\culture_markets_2024_to_now_closed_resolved_yesno_FINAL.xlsx
Shape сохранённого CSV: (19072, 4)

                                           question                 startDate               endDate  final_outcome
0     Will the Epstein documents name Jimmy Kimmel?  2024-01-03T14:11:38.915Z  2024-02-29T00:00:00Z              0
1          Will 2024 be the hottest year on record?  2024-01-16T21:50:24.112Z  2025-03-01T00:00:00Z              1
2  Andrew Tate guilty of human trafficking in 2024?  2024-01-17T21:17:16.187Z  2024-12-30T12:00:00Z              0
3                     Will America ban Zyn in 2024?  2024-01-25T17:27:39.723Z  2024-12-31T00:00:00Z              0
4             Will 'Deadpool 3' gross most in 2024?      2024-01-31T23:47:00Z  2024-12-29T00:00:00Z              0